// Generated by Apple Swift version 3.1 (swiftlang-802.0.51 clang-802.0.41)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UIColor;
@class NSCoder;

SWIFT_CLASS("_TtC14CSKitUniversal8CSButton")
@interface CSButton : UIButton
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic, copy) NSString * _Nullable text;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

SWIFT_CLASS("_TtC14CSKitUniversal24CSTextFieldContainerView")
@interface CSTextFieldContainerView : UIView
@property (nonatomic, readonly, copy) NSArray<UITextField *> * _Nullable textFields;
@property (nonatomic, readonly) NSInteger numberOfTextFields;
/// A Boolean value that determines whether the font size of each TextField should be adjusted to maintain a ratio with the size of the view. This property is true by default.
/// Setting it to false will always keep the font at the defaultFontSize.
@property (nonatomic) BOOL shouldAdjustFontSizeToContainer;
/// A Boolean value that determines whether the font size of each TextField should be adjusted when one of the TextFields is hidden. This property is true by default.
/// Setting this property to false will keep the font at
@property (nonatomic) BOOL shouldResizeFontWhenHidden;
@property (nonatomic) CGFloat defaultFontSize;
- (nonnull instancetype)initWithNumberOfTextFields:(NSInteger)numberOfTextFields withTitles:(NSArray<NSString *> * _Nonnull)withTitles frame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)toggleTextFieldVisibilityWithIndex:(NSInteger)index isHidden:(BOOL)isHidden;
- (void)setFontSize:(CGFloat)size;
@end

@class UIViewController;

SWIFT_CLASS("_TtC14CSKitUniversal8CSWindow")
@interface CSWindow : UIWindow
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithViewController:(UIViewController * _Nonnull)viewController;
@end


@interface UIColor (SWIFT_EXTENSION(CSKitUniversal))
/// Initializes and returns a color object using the specified opacity and RGB component values.
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     r: The red value of the color object on a scale from 0 to 255.
///   </li>
///   <li>
///     g: The green value of the color object on a scale from 0 to 255.
///   </li>
///   <li>
///     b: The blue value of the color object on a scale from 0 to 255.
///   </li>
///   <li>
///     a: The opacity value of the color object on a scale from 0 to 100.
///   </li>
/// </ul>
- (nonnull instancetype)initWithR:(CGFloat)r g:(CGFloat)g b:(CGFloat)b a:(CGFloat)a;
@end


@interface UITableViewController (SWIFT_EXTENSION(CSKitUniversal))
/// Automatically calls the dismiss method for the given UITableViewController.
- (void)back;
@end


@interface UIView (SWIFT_EXTENSION(CSKitUniversal))
/// Returns an instance of a UIView with translatesAutoresizingMaskIntoConstraints set to specified value.
- (nonnull instancetype)initWithAutoresizingToConstraints:(BOOL)autoresizingToConstraints;
@property (nonatomic) CGFloat cornerRadius;
/// Sets the width and color of the layer’s border.
- (void)setBorderWithWidth:(CGFloat)width color:(UIColor * _Nonnull)color;
@end


@interface UIViewController (SWIFT_EXTENSION(CSKitUniversal))
/// Used to dismiss the keyboard when the user taps the screen.
- (void)hideKeyboardWhenTappedAround;
/// Automatically dismisses an active keyboard.
- (void)dismissKeyboard;
/// Displays a UIAlertController with given title and message to alert the user of an error in their use of the application.
/// \param errorTitle The title of the Alert.
///
/// \param errorMessage The message to be displayed to the user.
///
/// \param buttonTitle The title of the button displayed.
///
- (void)displayErrorMessageWithErrorTitle:(NSString * _Nonnull)errorTitle errorMessage:(NSString * _Nonnull)errorMessage buttonTitle:(NSString * _Nonnull)buttonTitle;
@end


SWIFT_CLASS("_TtC14CSKitUniversal8Vector3D")
@interface Vector3D : NSObject <NSCoding>
/// The x component of the given vector.
@property (nonatomic) double x;
/// The y component of the given vector.
@property (nonatomic) double y;
/// The z component of the given vector.
@property (nonatomic) double z;
/// Magnitude of the given vector.
@property (nonatomic, readonly) double magnitude;
/// Creates a vector with the given components.
/// \param x The x component of the vector.
///
/// \param y The y component of the vector.
///
/// \param z The z component of the vector.
///
- (nonnull instancetype)initWithX:(double)x y:(double)y z:(double)z OBJC_DESIGNATED_INITIALIZER;
/// Creates a vector between two given points.
- (nonnull instancetype)initWithX1:(double)x1 y1:(double)y1 z1:(double)z1 x2:(double)x2 y2:(double)y2 z2:(double)z2;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// The string format of a Vector.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

#pragma clang diagnostic pop
